#ifndef TOKEN_H
#define TOKEN_H

typedef struct _token_t token_t;
typedef enum _token_class_t token_class_t;

enum _token_class_t{
    EOFF,
    ERRONEOUS,
    KEYWORD_PUT,
    KEYWORD_GET,
    KEYWORD_IF,
    KEYWORD_ELSE,
    KEYWORD_FOR,
    KEYWORD_IN,
    KEYWORD_TO,
    KEYWORD_WHILE,
    KEYWORD_TYPE,
    KEYWORD_FNC,
    KEYWORD_RETURN,
    KEYWORD_BREAK,
    KEYWORD_CONTINUE,
    KEYWORD_TRUE,
    KEYWORD_FALSE,
    KEYWORD_SWITCH,
    KEYWORD_WHEN,
    KEYWORD_DEFAULT,
    KEYWORD_AND,
    KEYWORD_OR,
    KEYWORD_NOT,
    KEYWORD_JUMP,
    DELIMETER_COLON,
    DELIMETER_SEMICOLON,
    DELIMETER_OPEN_PAR,
    DELIMETER_CLOS_PAR,
    DELIMETER_CURL_OPEN_PAR,
    DELIMETER_CURL_CLOS_PAR,
    DELIMETER_PLUS,
    DELIMETER_MINUS,
    DELIMETER_STAR,
    DELIMETER_PERCENTAGE,
    DELIMETER_ASSIGN,
    DELIMETER_LESS,
    DELIMETER_LESS_EQ,
    DELIMETER_GREATER,
    DELIMETER_GREATER_EQ,
    DELIMETER_EQUAL,
    DELIMETER_NOT_EQUAL,
    DELIMETER_DIVIDE_EQ,
    DELIMETER_MULT_EQ,
    DELIMETER_PLUS_EQ,
    DELIMETER_MINUS_EQ,
    DELIMETER_COMMA,
    DELIMETER_DOT,
    DELIMETER_LEFT_BRACKET,
    DELIMETER_RIGHT_BRACKET,
    DELIMETER_UNDERSCORE,
    DELEMTER_NOT_EQUAL,
    DELIMETER_SLASH,
    DELIMETER_QUESTION_MARK,
    KEYWORD_VOID,
    COMMENT,
    IDENTIFIER,
    CHR_LITERAL,
    STR_LITERAL,
    BOOL_TRUE,
    BOOL_FALSE,
    NUMBER_CONST,
    FLOAT_CONST
};
struct _token_t{
    token_class_t type;
    char* value;
    int line_no;
};

#endif